spring:
  data:
    mongodb:
      host: host.docker.internal
      port: 27017
      database: stackoverflow
      auto-index-creation: true

mongock:
  migration-scan-package:
    - empty
#    - com.wouterlefever.stackoverflow.changeset